# Generated by Django 5.2.4 on 2025-07-13 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f0c80c44-e5e0-4e56-86af-1e046751a19d'), primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('operation', 'Operation'), ('client', 'Client')], default='client', max_length=20)),
            ],
        ),
    ]
