# Generated by Django 5.2.4 on 2025-07-13 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6e7cec0-f77d-4db8-a967-6236a665f411'), primary_key=True, serialize=False),
        ),
    ]
