# Generated by Django 5.2.4 on 2025-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.URLField(default=None, null=True),
        ),
    ]
